#+STARTUP: entitiespretty

#+TITLE: Notes sobre I2C

* Nivell físic

1) Dues línies «open drain»: SDA, dades; SCL; clock.
2) Tensions típiques: 3.3V i 5.0V
3) Capacitància màxima bus 400 pF. Limita el nombre de nodes.
4) Massa comuna en tots el nodes.
5) Freqüència de clock arbitrària. Típiques: 100 kb/s, 400 kb/s. Pot
   arribar a 1 Mb/s i fins i tot 5Mb/s.
6) El fet que les línies siguin open drain, amb un pull-up que les
   sosté a 1, implica que diversos nodes les poden colocar a 0
   simultàniament: només són a 1 si cap node les coloca a 0.
7) En idle, ambdues línies són a 1. SDA només canvia quan SCL és 0
   excepte pels signals especials START i STOP.
8) En transmissió bàsica d'un bit, el transmissor posa SCL a low i SDA
   al bit escaient; després d'un retard per que es propagui, posa de
   de nou SCL a 1 i espera que efectivament sigui 1 ---hi ha retards a
   causa del comportament elèctric del circuït---; espera 4 us i
   transmet de nou.
9) Cada 8 bits de dades en una direcció, hi 1 bit de ACK en l'altra. O
   implica ACK i 1 NACK. Durant ACK el màstyer manté el control del
   rellotge i només canvia el sentit SDA.


* Nivell

1) Nodes són màster o esclaus.
   - màster genera clock i inicia la transmissió.
   - esclau escolta i contesta si cal.
2) Adreçament de nodes de 7 bits.
3) Bus multi-master. Poden haver-hi diversos nodes màster en el
   bus. Després  d'un missatge d'STOP, els rols de màster i esclau
   poden canviar.
4) Els rols i modes dels nodes són:
   | Rol    | Mode | Descripció                  |
   |--------+------+-----------------------------|
   | màster | Tx   | màster transmet a un esclau |
   |        | Rx   | màster rep d'un esclau      |
   | esclau | Tx   | esclau transmet a màster    |
   |        | Rx   | esclau rep d'un màster      |
5) El protocol envia adreces i dades de 8bits. Les adreces ocupen
   7bits i el 8è bit s'usa per indicar certes condicions (R/W, ACK)
6) Adreces i dades s'envien ordenades de MSB a LSB
7) Algunes condicions específiques s'envien per estats de
   sincronització especials entre les dues linies SDA i SCL.
   - START: falling edge de SDA amb SCL high
   - 

* Protocol bàsic

1) El màster envia START, seguit d'una adreça de 7bit i un bit més que
   indica si vol escriure (0) o llegir (1) de l'esclau.
2) Si l'esclau existeix al bus, contesta amb un bit ACK (0 per ack)
   per a aquesta adreça.
3) A continuació es transmeten les dades. Si el màster vol escriure,
   el màster envia bytes i per cadascún enviat l'esclau contesta amb
   ACK. Si el màster vol llegir, l'esclau envia dades i el màster
   respon amb ACK excepte pel darrer.
4) El màster acaba l'enviament amb STOP, excepte si vol retenir el bus
   per enviar un altre missatge. En aquest darrer cas, en comptes
   d'STOP envia un START ---es coneix com mode combinat---.
5) 

